In [12]:
import pandas as pd

In [17]:
ag_growth = pd.read_csv("datasets/micro_datasets/agri_timeline.csv")
industry_growth = pd.read_csv("datasets/micro_datasets/industry_timeline.csv")
manu_growth = pd.read_csv("datasets/micro_datasets/manufacturing_timeline.csv")
service_growth = pd.read_csv("datasets/micro_datasets/service_timeline.csv")

In [18]:
ag_growth

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.414389,2.312357,3.994806,2.151072,1.713093,3.780958,4.134563,2.961900,1.231300,NaN
2,Afghanistan,AFG,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-5.657218,5.971752,6.411059,-4.415311,17.459825,5.942340,-9.780634,-6.564078,2.060824,NaN
3,Africa Western and Central,AFW,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,3.504946,4.244629,4.918266,3.248648,2.343420,2.612906,3.136455,3.379935,1.725906,NaN
4,Angola,AGO,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,10.160481,3.852721,0.457775,-2.482599,-1.747257,2.843708,17.204850,3.939829,2.712516,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,17.924762,15.966571,-3.980439,-10.448860,12.409123,-5.761472,-2.491332,4.516932,-2.966124,NaN
262,"Yemen, Rep.",YEM,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-17.691194,12.534294,2.003686,7.419462,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,3.713848,5.671529,3.239914,-11.45212,1.109773,...,-3.637629,-5.151363,19.080359,0.492936,-6.521409,17.259515,5.566310,2.038402,-4.782619,NaN
264,Zambia,ZMB,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-7.736634,3.719521,9.788283,-21.177497,7.702659,17.206766,6.934456,-10.617078,-20.451846,NaN
265,Zimbabwe,ZWE,"Agriculture, forestry, and fishing, value adde...",NV.AGR.TOTL.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,-5.256535,-3.895121,10.035361,18.406940,-10.402825,4.149892,17.475076,6.152919,6.313705,NaN